def get_all_provinces_with_districts():
    def get_all_provinces():
    return {
        "adana": [
            "aladağ",
            "ceyhan",
            "çukurova",
            "imamoglu",
            "feke",
            "karaisali",
            "karataş",
            "kozan",
            "pozantı",
            "saimbeyli",
            "sarıçam",
            "seyhan",
            "tufanbeyli",
            "Adana Havalimanı",
            "yumurtalık",
            "yüreğir"
        ],
        "adıyaman": ["adıyaman", "adıyaman havalimani", "besni", "gerger", "gölbaşı", "kahta","sincik","samsat", "çelikhan", "tut"],
        "afyonkarahisar": ["afyonkarahisar", "afyonkarahisar havalimanı","cay","evciler","hocalar" ,"bayat","basmakcı","cobanlar","ihsaniye", "dazkırı", "dinar", "iscehisar","suhut","kızılören", "sinanpaşa", "sultandağı", "emirdag", "bolvadin"],
        "ağrı": ["merkez", "Ahmed-i Hani havalimani", "eleskirt","diyadin","patnos","doğubayazit", "hamur", "eleşkirt", "tutak","taslicay"],
        "aksaray": ["merkez", "ağaçören", "eskil", "güzelyurt","gülagac", "sarıyahşi", "ortaköy",  "sarıyahsi","Sultanhani"],
        "amasya": ["merkez", "göynücek", "gümüşhacıköy", "merzifon", "merzifon havalimani","suluova", "taşova", "hamamözü"],
        "Ankara": ["akyurt","ayas","bala","beypazari","elmadag","esenboga havalimani","etimesgut havalimani","cankaya", "evren","Güdül","Güvercinlik havalimani","haymana","kahramankazan","kalecik","Mürted havalimani","nallihan","kizilcahamam","kecioren", "mamak", "yenimahalle",  "altındağ", "etimesgut", "sincan", "gölbaşı", "polatlı","pursaklar","camlidere","cubuk","sereflikochisar"],
        "antalya": ["Antalya","Antalya havalimani","aksu","demre","elmali","finike" ,"alanya","korkuteli", "döşemealtı","kas","gazipasa havalimani", "gündogmus","konyaaltı","kumluca","muratpasa","ibradi","Saklikent" ,"kepez", "kemer", "manavgat", "serik", "gazipaşa", "akseki"],
        "artvin": ["merkez", "arhavi","kemalpasa", "şavşat", "borçka", "yusufeli", "hopa", "murgul", "savsat", "ardanuç"],
        "aydin": ["merkez", "efeler","kocarli", "incirliova","Çıldır havalimani","yenipazar","söke", "kuyucak", "bozdoğan", "karacasu", "nazilli","germencik","güzelcamli" ,"didim","Buharkent", "çine", "köşk","karpuzlu","kocarli","sultanhisar"],
        "balıkesir": ["merkez", "havran","karesi","balya","bandirma havalimani","erdek","balikesir havalimani", "altieylül","altinoluk","dursunbey", "bandırma", "burhaniye", "edremit", "ayvalık", "sındırgı", "gönen", "Gömeç","bigadiç","kepsut","manyas","marmara","susurluk","savastepe","ivrindi"],
        "bartın": ["merkez", "amasra", "kurucaşile", "ulus"],
        "bayburt": ["merkez", "aydintepe","demirözü"],
        "bilecik": ["merkez", "bozüyük", "pazaryeri", "yenipazar", "söğüt", "gölpazari", "osmaneli","inhisar"],
        "bingöl": ["merkez", "adakli", "bingöl havalimani", "yedisu", "genç", "yayladere", "karlıova", "kiğı","solhan"],
        "bitlis": ["nemrut kayak merkezi", "adilcevaz", "tatvan", "hizan", "güroymak", "ahlat", "mutki", "merkez"],
        "bolu": [ "gerede", "dörtdivan","göynük","kartalkaya kayak merkezi", "kıbrıscık","mengen","yeniçağa", "mudurnu", "seben"],
        "burdur": ["merkez", "bucak", "altinyayla","aglasun","kemer","Yesilova salda kayak merkezi","çeltikci","gölhisar", "karamanlı", "yeşilova", "tefenni", "çavdır"],
        "bursa": ["büyükorhan","gürsu","harmancik","keles","kestel","mustafakemalpasa","orhaneli","uludağ kayak merkezi","yenisehir havalimani","inegöl","iznik","nilüfer", "osmangazi", "yıldırım", "orhangazi", "mudanya", "karacabey", "gemlik"],
        "çanakkale": ["merkez", "Çanakkale Havalimanı","ayvacık","bayramiç","eceabat","ezine","gelibolu","gökceada","Gökçeada havalimani","yenice","biga", "gelibolu", "lapseki", "bozcaada",  "çan"],
        "çankırı": [ "atkaracalar", "bayramören","eldivan","ilgaz kayak merkezi","korgun","yaprakli","yildiztepe kayak merkezi","kurşunlu", "orta", "ilgaz", "şabanözü", "kızılırmak", "çerkeş"],
        "çorum": ["merkez", "alaca","bayat","dodurga","kargı","osmancik","oguzlar","ugurludag","iskilip", "sungurlu", "mecitözü", "laçin", "boğazkale", "ortaköy"],
        "denizli": ["merkez", "merkezefendi", "acıpayam","babadağ","baklan","bozkurt","buldan","güney","kale","pamukkale","sarayköy","çal","çameli","çardak","çardak havalimani", "beyağaç", "serinhisar", "tavas", "buldan", "honaz", "çivril"],
        "diyarbakır": ["diyarbakir","yenisehir","çermik","çüngüş","baglar","dicle","eğil","hazro","kocaköy","kulp", "bismil", "çınar", "silvan", "ergani", "kayapınar", "hani", "sur", "lice"],
         "düzce": ["merkez", "akçakoca", "kaynaşlı", "gölyaka", "cumayeri","gümüsova","yıgılca","cilimli"],
        "edirne": ["merkez","enez","hamzabeyli sinir kapisi","havsa","kapikule","lalapasa","meric","süloglu","ipsala", "keşan", "uzunköprü"],
        "elazığ": ["merkez","elazıg havalimani","alacakaya","agin","baskil","keban","kovancilar","sivrice kayak merkezi", "karakoçan", "maden", "sivrice", "palu", "keban", "aricak"],
        "erzincan": ["erzincan havalimani","ergan kayak merkezi","kemah","otlukbeli","refahiye","tercan","çayırlı", "üzümlü", "kemaliye", "iliç"],
        "erzurum": ["erzurum havalimani","aziziye","askale","hınıs","karayazi","karacoban","köpruköy","narman","oltu","olur","palandöken kayak merkezi", "palandöken", "yakutiye","çat","ispir", "şenkaya"],
        "eskişehir": [ "eskişehir havalimani","alpu","beylikova","günyüzü","han","hasan polatkan havalimani","mahmudiye","mihalgazi","mihalıççık","odunpazari","saricakaya","seyitgazi","sivrihisar","sivrihisar havalimani","çifteler","inönü","tepebaşı", "odunpazarı",  "beylikova"],
        "gaziantep": ["gaziantep havalimani","nurdağı", "şahinbey", "şehitkamil", "şehitkadir", "nizip", "karkamış", "oğuzeli","yavuzeli","islahiye","şehitkamil" ,"araban"],
        "giresun": ["merkez", "dereli","doğankent","eynesil","güce","keşap","piraziz","çamoluk","çanakçı","şebinkarahisar","espiye", "görele", "tirebolu", "bulancak", "alucra", "yağlıdere"],
        "gümüşhane": ["merkez","kelkit","torul zigana", "köse", "şiran", "torul", "kürtün"],
        "hakkari": ["merkez", "şemdinli", "yüksekova", "çukurca","yüksekova selahaddin eyyübi havalimani"],
        "hatay": ["hatay", "antakya", "altinozü","arsuz","belen","erzin","hassa","kumlu","kirikhan","payas","reyhanli","samandağ","defne", "dörtyol", "iskenderun", "yayladağı"],
        "ısparta": ["aksu","atabey","Davraz kayak merkezi","gelendost","gönen","süleyman demirel havalimani","sütcüler","uluborlu","yalvaç","yenişarbademli", "eğirdir",  "senirkent", "şarkikaraağaç", "keçiborlu"],
         "istanbul": ["istanbul havalimani","adalar","arnavutköy","atatürk havalimani","ataşehir","bakırköy","bayrampasa","bağcılar","basaksehir","beykoz","beylikdüzü","beyoğlu","besiktas","büyükcekmece","esenler","eyüpsultan","gaziosmanpasa","güngören","kadıköy","kartal","kağıthane","küçükcekmece","maltepe","pendik","sabiha gökcen havalimani","samandıra havalimani","sancaktepe","sariyer","sultanbeyli","sultangazi","tuzla","yavuz sultan selim köprüsü","zeytinburnu","çatalca","çekmeköy","ümraniye","üsküdar","itü maslak yerleşkesi","şile","kadıköy", "üsküdar", "beşiktaş", "fatih", "beyoğlu",  "avcılar", "bahçelievler", "esenyurt", "silivri"],
        "izmir": ["merkez","adnan menderes havalimani","aliağa","balcova","bayrakli","bayindir","bergama","beydağ","bozdağ kayak merkezi","dikili","foça","güzelbahçe","kaklıç havalimani","karabağlar","karaburun","kemalpasa","kiraz","kınık","menderes","menemen","narlıdere","seferihisar","selçuk","selcuk efes havalimani","tire","çiğli","çiğli havalimani", "konak", "karşıyaka", "gaziemir", "buca", "bornova", "torbalı", "çeşme", "urla","Ödemis"],
        "kahramanmaraş": ["merkez", "andirin","ekinözü","nurhak","onikişubat","türkoglu","cağlayancerit","dulkadiroğlu", "onikişubat", "elbistan", "afşin", "pazarcık",  "göksun"],
        "karabük": ["merkez", "eflani","eskipazar","ovacik","safranbolu", "yenice"],
        "karaman": ["merkez","ayranci", "basyayla","ermenek", "kazımkarabekir","sariveliler"],
        "kars": ["merkez","akyaka","harakani havalimani","sarikamis kayak merkezi","susuz", "arpaçay", "selim", "digor", "kağızman", "sarıkamış"],
        "kastamonu": ["merkez","kastamonu havalimani","abana","arac","azdavay","ağlı","bozkurt","cide","devrekani","doğanyurt","hanönü","küre","seydiler","tasköprü","catalzeytin","ihsangazi","inebolu","senpazar", "tosya", "daday", "pınarbaşı"],
        "kayseri": ["kayseri", "akkisla","erciyes kayak merkezi","felahiye","hacilar","pinarbasi","sarioglan","sariz","tomarza","yahyali","yesilhisar","incesu","melikgazi", "kocasinan", "talas", "hacılar", "develi", "bünyan", "Özvatan"],
        "kırıkkale": ["merkez", "bahşili","sulakyurt","çelebi","keskin", "delice", "karakeçili", "yahşihan", "balışeyh"],
        "kırklareli": ["merkez", "lüleburgaz", "pınarhisar", "vize", "babaeski", "kofçaz", "pehlivanköy","demirköy"],
        "kırşehir": ["merkez", "mucur", "kaman", "akpınar","akçakent", "çiçekdağı", "boztepe"],
        "konya": ["Konya","konya havalimani","ahirli","akören","altınekin","beyşehir","bozkır","derbent","derebucak","doğanhisar","emirgazi","güneysınır","hadim","halkapınar","Ilgın","kadınhanı","karapınar","karatay","kulu","selcuklu","seydişehir","taskent","tuzlukcu","yalıhüyük","yunak","çeltik","çumra", "selçuklu", "karatay", "meram", "akşehir", "ereğli", "hüyük", "cihanbeyli", "sarayönü"],
        "kocaeli": [ "başiskele","Cengiz topel havalimani","dilovasi",  "gölcük","kandıra","karamürsel","kartepe","kartepe kayak merkezi", "izmit", "gebze", "kartepe", "derince", "çayırova", "darıca", "körfez"],
        "kütahya": ["merkez", "kütahya havalimani","simav", "tavşanlı", "emet", "domaniç", "gediz", "aslanapa","altintas","dumlupınar","gediz","hisarcik","murat dağı kayak merkezi","pazarlar","zafer havalimani","çavdarhisar","şaphane"],
        "malatya": ["merkez", "malatya havalimani","arapgir","arguvan","darende","doğanyol","doğanşehir","Kale","tulga havalimani","yazıhan","yeşilyurt","akçadağ", "battalgazi", "hekimhan", "pütürge", "yarıklı", "kuluncak"],
        "manisa": ["merkez","ahmetli","akhisar","akhisar havalimani","alasehir","demirci","gölmarmara","kula","kırkağac","sarıgöl","selendi","spil dağı milli parki","yunusemre","sehzadeler" ,"salihli", "gördes", "turgutlu", "saruhanlı", "köprübaşı", "soma", "demirtaş"],
        "mardin": ["merkez","mardin havalimani","kiziltepe","nusaybin","ömerli","yeşilli", "midyat", "nusaybin", "derik", "dargeçit", "mazıdağı", "artuklu", "savur"],
        "muğla": [ "bodrum", "marmaris","bodrum ımsık havalimani","dalaman","dalaman havalimani","fethiye","kavaklıdere","köyceğiz","marmaris","mentese","milas bodrum havalimani","seydikemer","ula","yatağan", "datça",  "milas", "ortaca"],
        "muş": ["merkez", "muş havalimani","bulanık", "malazgirt", "varto", "korkut", "hasköy"],
        "nevşehir": ["merkez","acıgöl","göreme kapadokya","kapadokya havalimani","kozakli","Ürgüp", "avanos", "derinkuyu", "gülşehir", "hacıbektaş"],
        "niğde": ["merkez", "altunhisar", "bor", "ulukışla","çamardı", "çiftlik"],
        "ordu": ["merkez", "ordu giresun havalimani","akkuş","altinordu","aybasti","gülyali","gürgentepe","kabatas","kumru","mesudiye","perşembe","ulubey","çamaş","çambaşı kayak merkezi","çatalpınar","çaybaşı","ikizce","ünye", "gölköy", "fatsa", "niksar", "korgan", "kabadüz", "gölkaya"],
        "osmaniye": ["merkez", "düziçi", "toprakkale", "hasanbeyli", "sumbas", "bahçe","kadirli"],
        "rize": ["merkez", "ardeşen","rize-artvin havalani", "derepazari","fındıklı","güneysu","hemşin","kalkandere","çamlıhemşin ayder","çayeli","ikizdere","iyidere","çamlıhemşin", "ardanuç", "çayeli", "pazar"],
        "sakarya": [ "adapazarı", "arifiye","erenler","ferizli","geyve","hendek","karapürçek","karasu","kaynarca","kocaali","pamukova","söğütlü","taraklı","serdivan", "sapanca", "karasu", "akyazı", "hendek"],
        "samsun": ["Samsun","alaçam","asarcık","atakum","ayvacık","canik","kavak","ladik","kayak merkezi", "tekkeköy", "vezirköprü", "bafra", "havza", "ondokuzmayıs","salıpazarı","terme","yakakent","çarşamba","çarşamba havalimani","ilkadim"],
        "siirt": ["merkez","siirt havalimani","şirvan" ,"tillo", "kurtalan", "pervari", "baykan", "eruh"],
        "sinop": ["merkez", "sinop havalimani","ayancik","dikmen","erfelek","gerze","türkeli","boyabat", "erenkaya", "durağan", "saraydüzü", "ayancık"],
        "sivas": ["merkez", "akıncılar","altınyayla","doğanşar","gemerek", "gürün","hafik","koyulhisar","nuri demirağ havalimani","ulaş","yıldızdağı kayak merkezi","zara","imranli","şarkışla","kangal", "divriği", "gölova", "suşehri", "yıldızeli"],
        "tekirdağ": ["merkez", "ergene","kapakli","marmaraereğlisi","muratli","saray","çorlu havalimani","şarköy","süleymanpaşa", "çorlu", "malkara", "hayrabolu", "çerkezköy"],
        "tokat": ["merkez", "tokat havalimani","almus","artova","başçiftlik","erbaa","pazar","sulusaray","yeşilyurt", "zile", "reşadiye", "niksar", "turhal"],
        "trabzon": ["Trabzon", "trabzon havalimani","arakli","arsin","düzköy","hayrat","köprübasi","maçka altindere","sürmene","tonya","uzungöl","vakfıkebir","çarşıbaşı","çaykara","Şalpazari","ortahisar","akçaabat", "yomra", "sürmene", "of", "maçka"],
        "tunceli": ["merkez", "hozat","mazgirt","ovacık","pertek","nazimiye", "pülümür",  "çemişgezek"],
         "uşak": ["merkez","uşak havalimani","eşme","ulubey","banaz", "sivaslı",  "karahallı"],
        "van": [ "edremit","başkale","erciş","ferit melen havalimani","gürpınar","saray","Tuşba ","çaldıran","Özalp","ipekyolu", "gevaş", "çatak", "bahçesaray", "muradiye"],
        "yalova": ["merkez","yalova havalimani","çiftlikköy", "çınarcık", "armutlu", "altınova", "termal"],
        "yozgat": ["merkez", "aydıncık","boğazlıyan","kadışehri","sarikaya","yenifakili","yerköy","çandır","çayıralan","çekerek","şefaatli","sorgun", "yerköy", "çayıralan", "akdağmadeni", "saraykent"],
        "zonguldak": ["merkez",  "alaplı", "devrek", "ereğli", "çaycuma","gökçebey","kilimli","kozlu","çaycuma","çaycuma havalimanı"],
    }